name: Run All Tests

on:
    pull_request:
        branches: ['main']
    workflow_dispatch: # allows manual run from GitHub UI

jobs:
    run-all-tests:
        #    runs-on: ubuntu-latest
        #    runs-on: windows-latest
        strategy:
            matrix:
                # Available GitHub-hosted runner types see:
                # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
                os:
                    [
                        windows-latest,
                        windows-2022,
                        windows-11-arm,
                        ubuntu-latest,
                        ubuntu-24.04,
                        ubuntu-24.04-arm,
                        macos-latest,
                        macos-13,
                    ]
        runs-on: ${{ matrix.os }}
        #runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20' # adjust as needed

            - name: Print Node.js version
              run: node --version

            - name: Install dependencies
              run: npm ci # npm clean-install (installs without changing package-lock.json)

            - name: Build # So that dist/ gets updated too.
              run: npm run build

            - name: Run Specific Test
              run: |
                  echo "Running test: ${{ github.event.inputs.testName }}"
                  npm run ci:test:smoke
